#  _____            __                                      _     _                 
# |_   _|          / _|                                    | |   (_)                
#   | |    _ __   | |_    ___    _ __   _ __ ___     __ _  | |_   _    ___    _ __  
#   | |   | '_ \  |  _|  / _ \  | '__| | '_ ` _ \   / _` | | __| | |  / _ \  | '_ \ 
#  _| |_  | | | | | |   | (_) | | |    | | | | | | | (_| | | |_  | | | (_) | | | | |
# |_____| |_| |_| |_|    \___/  |_|    |_| |_| |_|  \__,_|  \__| |_|  \___/  |_| |_|
                                                                                  

discord-message: "Discord Server Link"

youtube-message: "YouTube Channel"

tiktok-message: "TikTok Channel"